version: '3.1'
services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: exampledb

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
    